name: "Omega Zirkel - Tools"
main: de.omegazirkel.risingworld.OZTools
version: 0.1.0
author: "Maik 'Devidian' Laschober"
team: "Omega Zirkel"
description: "This Plugin is providing useful stuff for other Plugins"
license: N/A
website: N/A